# Generated by Django 4.2.7 on 2025-01-09 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_link_activitylog_short_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('reason', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('url_attempted', models.URLField(max_length=2000)),
                ('user_agent', models.TextField()),
                ('request_data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='created_by_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='url',
            name='is_malicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='url',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='url',
            name='url_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['short_code'], name='shortener_u_short_c_50dfff_idx'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['url_hash'], name='shortener_u_url_has_333cec_idx'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['created_by_ip', 'created_at'], name='shortener_u_created_303f51_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivity',
            index=models.Index(fields=['ip_address', 'timestamp'], name='shortener_s_ip_addr_a8cc92_idx'),
        ),
        migrations.AddIndex(
            model_name='blockeddomain',
            index=models.Index(fields=['domain'], name='shortener_b_domain_fcb7d6_idx'),
        ),
    ]
