# Generated by Django 4.2.7 on 2025-01-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_clickanalytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClickAnalytics',
        ),
    ]
