# Generated by Django 4.2.7 on 2025-01-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0010_delete_clickanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_type', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('user_agent', models.TextField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.url')),
            ],
            options={
                'indexes': [models.Index(fields=['url', 'timestamp'], name='shortener_c_url_id_3b627b_idx'), models.Index(fields=['url', 'country'], name='shortener_c_url_id_1881e0_idx')],
            },
        ),
    ]
