# Generated by Django 4.2.7 on 2025-03-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0012_clickevent_delete_clicklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='referer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='device_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='short_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['short_code'], name='shortener_a_short_c_b5efba_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='shortener_a_timesta_6c144c_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['clicked_at'], name='shortener_c_clicked_d60fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['url', 'clicked_at'], name='shortener_c_url_id_ea56c0_idx'),
        ),
    ]
