# Generated by Django 5.2 on 2025-05-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0013_activitylog_ip_address_activitylog_referer_and_more'),
    ]

    operations = [
    ]
