# Generated by Django 5.2 on 2025-05-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0014_auto_20250504_1449'),
    ]

    operations = [
    ]
